repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Lint
        entry: uv run ruff check --fix
        language: system
        always_run: true
        files: \.py$

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        always_run: true
        files: \.py$
