# Single experiment configuration
# This is a template you can copy into workspace and edit

script = "scripts/simulate_Dp.py"
output_dir = "results/simulate_Dp"
parameters_file = "parameters/Dp_default.csv"
log_file = "logs/Dp_simulator_log.jsonl"
description = "Simulating Dp example"
