project:
  type: default

format:
  html:
    embed-resources: true
    standalone: true
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    fig-width: 12
    fig-height: 8
